package com.training.java817.module3.after;

import java.time.LocalDate;
import java.util.Objects;

/**
 * =============================================================================
 * MODULE 3 – WORKSHOP: AFTER STATE
 * Task 1: Employee POJO → Java 17 Record
 * =============================================================================
 *
 * What changed:
 *  - 100+ line POJO replaced by a ~25 line record.
 *  - Accessors now have no "get" prefix (employeeId(), name(), etc.).
 *  - equals/hashCode/toString auto-generated by the compiler.
 *  - Compact constructor handles validation cleanly.
 *  - Added a meaningful isHighSalary() helper method.
 *  - Added a static factory method pending() for convenience.
 *
 * Benefits:
 *  - Zero boilerplate – every line carries meaning.
 *  - Immutable by default – all fields are final.
 */
public record EmployeeRecord(
        String    employeeId,
        String    name,
        double    salary,
        String    departmentId,
        String    managerId,
        String    location,
        String    jobTitle,
        LocalDate joinDate,
        LocalDate reviewDate,
        String    status
) {
    // --- Compact constructor: validation without repeating assignments ---
    public EmployeeRecord {
        Objects.requireNonNull(employeeId,   "employeeId required");
        Objects.requireNonNull(name,         "name required");
        Objects.requireNonNull(departmentId, "departmentId required");
        Objects.requireNonNull(managerId,    "managerId required");
        Objects.requireNonNull(location,     "location required");
        Objects.requireNonNull(jobTitle,     "jobTitle required");
        Objects.requireNonNull(joinDate,     "joinDate required");
        Objects.requireNonNull(reviewDate,   "reviewDate required");
        Objects.requireNonNull(status,       "status required");
        if (salary < 0) {
            throw new IllegalArgumentException("salary must be >= 0, was: " + salary);
        }
    }

    // --- Derived/computed methods ---

    /** Business rule: employees with salary above 100K are classified as high earners. */
    public boolean isHighSalary() {
        return salary > 100_000.0;
    }

    /** Business rule: notice period days depend on job title. */
    public int expectedNoticePeriodDays() {
        return switch (jobTitle) {
            case "ENGINEER"  -> 60;
            case "MANAGER"   -> 90;
            case "DIRECTOR"  -> 120;
            case "ANALYST"   -> 30;
            default          -> 30;
        };
    }

    // --- Static factory methods ---

    /** Creates an ONBOARDING employee with today's join date and a future review date. */
    public static EmployeeRecord pending(String employeeId, String name, double salary,
                                         String departmentId, String managerId,
                                         String location, String jobTitle) {
        LocalDate today = LocalDate.now();
        return new EmployeeRecord(
                employeeId, name, salary, departmentId, managerId,
                location, jobTitle, today, today.plusDays(90), "ONBOARDING");
    }

    /** Creates a copy of this record with an updated status (copy-with pattern). */
    public EmployeeRecord withStatus(String newStatus) {
        return new EmployeeRecord(
                employeeId, name, salary, departmentId, managerId,
                location, jobTitle, joinDate, reviewDate, newStatus);
    }
}
