package com.training.java817.module3.after;

import java.time.LocalDate;
import java.util.Objects;

/**
 * =============================================================================
 * MODULE 3 – WORKSHOP: AFTER STATE
 * Task 1: TradeTransaction POJO → Java 17 Record
 * =============================================================================
 *
 * What changed:
 *  - 100+ line POJO replaced by a ~20 line record.
 *  - Getters now have no "get" prefix (tradeId(), symbol(), etc.).
 *  - equals/hashCode/toString auto-generated by the compiler.
 *  - Compact constructor handles validation cleanly.
 *  - Added a meaningful isHighValue() helper method – records can have methods.
 *  - Added a static factory method draft() for convenience.
 *
 * Benefits:
 *  - Zero boilerplate – every line carries meaning.
 *  - Immutable by default – all fields are final.
 *  - No third-party annotation processors needed (bye, Lombok @Data).
 */
public record TradeTransactionRecord(
        String   tradeId,
        String   symbol,
        double   notional,
        String   counterpartyId,
        String   traderId,
        String   currency,
        String   assetClass,
        LocalDate tradeDate,
        LocalDate settlementDate,
        String   status
) {
    // --- Compact constructor: validation without repeating assignments ---
    public TradeTransactionRecord {
        Objects.requireNonNull(tradeId,        "tradeId required");
        Objects.requireNonNull(symbol,         "symbol required");
        Objects.requireNonNull(counterpartyId, "counterpartyId required");
        Objects.requireNonNull(traderId,       "traderId required");
        Objects.requireNonNull(currency,       "currency required");
        Objects.requireNonNull(assetClass,     "assetClass required");
        Objects.requireNonNull(tradeDate,      "tradeDate required");
        Objects.requireNonNull(settlementDate, "settlementDate required");
        Objects.requireNonNull(status,         "status required");
        if (notional < 0) {
            throw new IllegalArgumentException("notional must be >= 0, was: " + notional);
        }
    }

    // --- Derived/computed methods ---

    /** Business rule: trades above 1M are classified as high-value. */
    public boolean isHighValue() {
        return notional > 1_000_000.0;
    }

    /** Business rule: number of settlement days depends on asset class. */
    public int expectedSettlementDays() {
        return switch (assetClass) {
            case "EQUITY"       -> 2;
            case "FIXED_INCOME" -> 1;
            case "FOREX"        -> 2;
            case "COMMODITY"    -> 5;
            default             -> 3;
        };
    }

    // --- Static factory methods ---

    /** Creates a DRAFT trade with today's date and T+2 settlement. */
    public static TradeTransactionRecord draft(String tradeId, String symbol,
                                               double notional, String counterpartyId,
                                               String traderId, String currency,
                                               String assetClass) {
        LocalDate today = LocalDate.now();
        return new TradeTransactionRecord(
                tradeId, symbol, notional, counterpartyId, traderId,
                currency, assetClass, today, today.plusDays(2), "DRAFT");
    }

    /** Creates an executed copy of this trade (wither / copy-with pattern). */
    public TradeTransactionRecord withStatus(String newStatus) {
        return new TradeTransactionRecord(
                tradeId, symbol, notional, counterpartyId, traderId,
                currency, assetClass, tradeDate, settlementDate, newStatus);
    }
}
