package com.training.java817.module2.records;

import java.time.LocalDate;
import java.util.Objects;

/**
 * =============================================================================
 * MODULE 2 – RECORDS (JEP 395, Java 16 GA)
 * =============================================================================
 *
 * THEORY
 * ------
 * A record is a special, restricted kind of class designed to be a transparent,
 * immutable carrier of data.  Given a set of fields (the "record components"),
 * the compiler automatically generates:
 *   • A canonical constructor
 *   • A public accessor method per component (same name, no "get" prefix)
 *   • equals() and hashCode() based on ALL components
 *   • toString() that prints all components
 *
 * PROBLEM SOLVED
 * --------------
 * 1. Eliminates 50–100 lines of DTO/POJO boilerplate.
 * 2. Guarantees immutability – all fields are final by default.
 * 3. Removes dependency on third-party code generators like Lombok.
 * 4. Makes Data Transfer Objects and Value Objects first-class citizens
 *    in the language.
 *
 * RULES & LIMITATIONS
 * --------------------
 *  • Cannot extend another class (already extends java.lang.Record).
 *  • Cannot be abstract.
 *  • All fields are implicitly private final.
 *  • Can implement interfaces.
 *  • Can have static fields/methods.
 *  • Can have custom constructors and methods.
 *  • Can have compact constructors (no parameter list) for validation.
 */
public class RecordsExample {

    // =========================================================================
    // BEFORE – Traditional POJO (Data Transfer Object)
    // =========================================================================

    /**
     * Before Java 16: a typical EmployeeDetails DTO required ~80 lines of code.
     * This class shows the full boilerplate.
     */
    public static class EmployeePojo {
        private final String id;
        private final String name;
        private final double salary;
        private final String departmentId;
        private final LocalDate hireDate;
        private final String status;

        public EmployeePojo(String id, String name, double salary,
                            String departmentId, LocalDate hireDate,
                            String status) {
            this.id           = Objects.requireNonNull(id,           "id required");
            this.name         = Objects.requireNonNull(name,         "name required");
            this.salary       = salary;
            this.departmentId = Objects.requireNonNull(departmentId, "departmentId required");
            this.hireDate     = Objects.requireNonNull(hireDate,     "hireDate required");
            this.status       = Objects.requireNonNull(status,       "status required");
        }

        public String getId()           { return id; }
        public String getName()         { return name; }
        public double getSalary()       { return salary; }
        public String getDepartmentId() { return departmentId; }
        public LocalDate getHireDate()  { return hireDate; }
        public String getStatus()       { return status; }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof EmployeePojo)) return false;
            EmployeePojo that = (EmployeePojo) o;
            return Double.compare(that.salary, salary) == 0
                    && Objects.equals(id, that.id)
                    && Objects.equals(name, that.name)
                    && Objects.equals(departmentId, that.departmentId)
                    && Objects.equals(hireDate, that.hireDate)
                    && Objects.equals(status, that.status);
        }

        @Override
        public int hashCode() {
            return Objects.hash(id, name, salary, departmentId, hireDate, status);
        }

        @Override
        public String toString() {
            return "EmployeePojo{" +
                    "id='" + id + '\'' +
                    ", name='" + name + '\'' +
                    ", salary=" + salary +
                    ", departmentId='" + departmentId + '\'' +
                    ", hireDate=" + hireDate +
                    ", status='" + status + '\'' +
                    '}';
        }
    }

    // =========================================================================
    // AFTER – Java 16 Record  (one line replaces ~80 lines above)
    // =========================================================================

    /**
     * Exactly the same DTO – expressed as a record.
     * equals, hashCode, toString, accessors, and the canonical constructor
     * are all auto-generated by the compiler.
     */
    public record EmployeeRecord(
            String id,
            String name,
            double salary,
            String departmentId,
            LocalDate hireDate,
            String status
    ) {
        // --- Compact constructor: validation without repeating field assignments ---
        public EmployeeRecord {
            Objects.requireNonNull(id,           "id required");
            Objects.requireNonNull(name,         "name required");
            Objects.requireNonNull(departmentId, "departmentId required");
            Objects.requireNonNull(hireDate,     "hireDate required");
            Objects.requireNonNull(status,       "status required");
            if (salary < 0) throw new IllegalArgumentException("salary must be >= 0");
        }

        // --- Custom method: derived value (records CAN have instance methods) ---
        public boolean isHighSalary() {
            return salary > 100_000.0;
        }

        // --- Static factory method ---
        public static EmployeeRecord pending(String id, String name, double salary,
                                             String departmentId) {
            return new EmployeeRecord(id, name, salary,
                    departmentId, LocalDate.now(), "ONBOARDING");
        }
    }

    // =========================================================================
    // Nested / Generic records
    // =========================================================================

    /** A generic Pair record – useful for returning two related values. */
    public record Pair<A, B>(A first, B second) {}

    /** Nested records compose naturally. */
    public record EmployeeConfirmation(
            EmployeeRecord employee,
            String confirmationRef,
            LocalDate confirmedAt
    ) {}

    // =========================================================================
    // Records implement interfaces
    // =========================================================================

    public interface Auditable {
        String auditSummary();
    }

    public record AuditedEmployee(String employeeId, String action, String performedBy)
            implements Auditable {
        @Override
        public String auditSummary() {
            return String.format("[AUDIT] %s performed '%s' on employee %s",
                    performedBy, action, employeeId);
        }
    }

    // demo main
    public static void main(String[] args) {
        EmployeeRecord emp = EmployeeRecord.pending("E001", "Alice", 95_000, "D01");
        System.out.println(emp);
        System.out.println("Is high salary: " + emp.isHighSalary());
        System.out.println("Name          : " + emp.name());     // accessor – no "get" prefix

        EmployeeRecord emp2 = EmployeeRecord.pending("E001", "Alice", 95_000, "D01");
        System.out.println("equals        : " + emp.equals(emp2)); // probably false (hireDate differs by ms)

        AuditedEmployee audit = new AuditedEmployee("E001", "PROMOTE", "john.doe");
        System.out.println(audit.auditSummary());
    }
}
