package com.training.java817.module2.sealedclasses;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Module 2 – Sealed Classes (JEP 409)")
class SealedClassesExampleTest {

    private SealedClassesExample ex;

    @BeforeEach
    void setUp() { ex = new SealedClassesExample(); }

    @Test
    @DisplayName("describeEvent: EmployeeHired contains name and salary")
    void describeEvent_hired_containsNameAndSalary() {
        String result = ex.describeEvent(new SealedClassesExample.EmployeeHired(
                "E001", "Alice", 85_000));
        assertTrue(result.contains("Alice"));
        assertTrue(result.contains("85000.00"));
    }

    @Test
    @DisplayName("describeEvent: EmployeeUpdated contains new salary")
    void describeEvent_updated_containsNewSalary() {
        String result = ex.describeEvent(new SealedClassesExample.EmployeeUpdated(
                "E002", 90_000));
        assertTrue(result.contains("90000.00"));
    }

    @Test
    @DisplayName("describeEvent: EmployeePromoted contains title and salary")
    void describeEvent_promoted_containsTitleAndSalary() {
        String result = ex.describeEvent(new SealedClassesExample.EmployeePromoted(
                "E003", "SENIOR_ENGINEER", 105_000));
        assertTrue(result.contains("105000.00"));
        assertTrue(result.contains("SENIOR_ENGINEER"));
    }

    @Test
    @DisplayName("describeEvent: EmployeeTerminated contains termination reason")
    void describeEvent_terminated_containsReason() {
        String result = ex.describeEvent(new SealedClassesExample.EmployeeTerminated(
                "E004", "Voluntary resignation"));
        assertTrue(result.contains("Voluntary resignation"));
    }

    // --- Record equality (auto-generated) ---

    @Test
    @DisplayName("Record equality: two identical EmployeeHired events are equal")
    void employeeHired_equality() {
        var e1 = new SealedClassesExample.EmployeeHired("E001", "Alice", 85_000);
        var e2 = new SealedClassesExample.EmployeeHired("E001", "Alice", 85_000);
        assertEquals(e1, e2);
    }

    @Test
    @DisplayName("Record equality: different names produce different records")
    void employeeHired_differentName_notEqual() {
        var e1 = new SealedClassesExample.EmployeeHired("E001", "Alice", 85_000);
        var e2 = new SealedClassesExample.EmployeeHired("E001", "Bob",   85_000);
        assertNotEquals(e1, e2);
    }

    // --- Sealed type hierarchy ---

    @Test
    @DisplayName("Sealed interface: EmployeeHired IS-A EmployeeEvent")
    void employeeHired_isInstanceOfEmployeeEvent() {
        SealedClassesExample.EmployeeEvent event =
                new SealedClassesExample.EmployeeHired("E001", "Alice", 85_000);
        assertInstanceOf(SealedClassesExample.EmployeeEvent.class, event);
    }

    @Test
    @DisplayName("Sealed interface: EmployeeTerminated IS-A EmployeeEvent")
    void employeeTerminated_isInstanceOfEmployeeEvent() {
        SealedClassesExample.EmployeeEvent event =
                new SealedClassesExample.EmployeeTerminated("E002", "Limit exceeded");
        assertInstanceOf(SealedClassesExample.EmployeeEvent.class, event);
    }

    // --- toString (auto-generated by record) ---

    @Test
    @DisplayName("Record toString: contains component values")
    void employeePromoted_toString_containsValues() {
        String str = new SealedClassesExample.EmployeePromoted("E001", "LEAD", 120_000).toString();
        assertTrue(str.contains("E001"));
        assertTrue(str.contains("LEAD"));
        assertTrue(str.contains("120000.0"));
    }
}
