package com.training.java817.module2.sealedclasses;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Module 2 – Sealed Classes (JEP 409)")
class SealedClassesExampleTest {

    private SealedClassesExample ex;

    @BeforeEach
    void setUp() { ex = new SealedClassesExample(); }

    @Test
    @DisplayName("describeEvent: TradeCreated contains symbol and notional")
    void describeEvent_created_containsSymbolAndNotional() {
        String result = ex.describeEvent(new SealedClassesExample.TradeCreated(
                "T001", "AAPL", 1_500_000));
        assertTrue(result.contains("AAPL"));
        assertTrue(result.contains("1500000.00"));
    }

    @Test
    @DisplayName("describeEvent: TradeUpdated contains new notional")
    void describeEvent_updated_containsNewNotional() {
        String result = ex.describeEvent(new SealedClassesExample.TradeUpdated(
                "T002", 750_000));
        assertTrue(result.contains("750000.00"));
    }

    @Test
    @DisplayName("describeEvent: TradeExecuted contains venue and price")
    void describeEvent_executed_containsVenueAndPrice() {
        String result = ex.describeEvent(new SealedClassesExample.TradeExecuted(
                "T003", "NYSE", 182.50));
        assertTrue(result.contains("182.5"));
        assertTrue(result.contains("NYSE"));
    }

    @Test
    @DisplayName("describeEvent: TradeRejected contains rejection reason")
    void describeEvent_rejected_containsReason() {
        String result = ex.describeEvent(new SealedClassesExample.TradeRejected(
                "T004", "Insufficient funds"));
        assertTrue(result.contains("Insufficient funds"));
    }

    // --- Record equality (auto-generated) ---

    @Test
    @DisplayName("Record equality: two identical TradeCreated events are equal")
    void tradeCreated_equality() {
        var e1 = new SealedClassesExample.TradeCreated("T001", "AAPL", 1_000_000);
        var e2 = new SealedClassesExample.TradeCreated("T001", "AAPL", 1_000_000);
        assertEquals(e1, e2);
    }

    @Test
    @DisplayName("Record equality: different symbols produce different records")
    void tradeCreated_differentSymbol_notEqual() {
        var e1 = new SealedClassesExample.TradeCreated("T001", "AAPL", 1_000_000);
        var e2 = new SealedClassesExample.TradeCreated("T001", "MSFT", 1_000_000);
        assertNotEquals(e1, e2);
    }

    // --- Sealed type hierarchy ---

    @Test
    @DisplayName("Sealed interface: TradeCreated IS-A TradeEvent")
    void tradeCreated_isInstanceOfTradeEvent() {
        SealedClassesExample.TradeEvent event =
                new SealedClassesExample.TradeCreated("T001", "AAPL", 1_000_000);
        assertInstanceOf(SealedClassesExample.TradeEvent.class, event);
    }

    @Test
    @DisplayName("Sealed interface: TradeRejected IS-A TradeEvent")
    void tradeRejected_isInstanceOfTradeEvent() {
        SealedClassesExample.TradeEvent event =
                new SealedClassesExample.TradeRejected("T002", "Limit exceeded");
        assertInstanceOf(SealedClassesExample.TradeEvent.class, event);
    }

    // --- toString (auto-generated by record) ---

    @Test
    @DisplayName("Record toString: contains component values")
    void tradeExecuted_toString_containsValues() {
        String str = new SealedClassesExample.TradeExecuted("T001", "NYSE", 182.5).toString();
        assertTrue(str.contains("T001"));
        assertTrue(str.contains("NYSE"));
        assertTrue(str.contains("182.5"));
    }
}
